
export const timezones = [
    { "value": "Pacific/Niue", "label": "Pacific/Niue (UTC-11:00)" },
    { "value": "Pacific/Pago_Pago", "label": "Pacific/Pago_Pago (UTC-11:00)" },
    { "value": "Pacific/Honolulu", "label": "Pacific/Honolulu (UTC-10:00)" },
    { "value": "Pacific/Rarotonga", "label": "Pacific/Rarotonga (UTC-10:00)" },
    { "value": "Pacific/Tahiti", "label": "Pacific/Tahiti (UTC-10:00)" },
    { "value": "Pacific/Marquesas", "label": "Pacific/Marquesas (UTC-09:30)" },
    { "value": "America/Adak", "label": "America/Adak (UTC-09:00)" },
    { "value": "Pacific/Gambier", "label": "Pacific/Gambier (UTC-09:00)" },
    { "value": "America/Anchorage", "label": "America/Anchorage (UTC-08:00)" },
    { "value": "America/Los_Angeles", "label": "America/Los_Angeles (UTC-07:00)" },
    { "value": "America/Denver", "label": "America/Denver (UTC-06:00)" },
    { "value": "America/Chicago", "label": "America/Chicago (UTC-05:00)" },
    { "value": "America/New_York", "label": "America/New_York (UTC-04:00)" },
    { "value": "America/Caracas", "label": "America/Caracas (UTC-04:00)" },
    { "value": "America/Halifax", "label": "America/Halifax (UTC-03:00)" },
    { "value": "America/Sao_Paulo", "label": "America/Sao_Paulo (UTC-03:00)" },
    { "value": "America/St_Johns", "label": "America/St_Johns (UTC-02:30)" },
    { "value": "Atlantic/Cape_Verde", "label": "Atlantic/Cape_Verde (UTC-01:00)" },
    { "value": "Atlantic/Azores", "label": "Atlantic/Azores (UTC+00:00)" },
    { "value": "Europe/London", "label": "Europe/London (UTC+01:00)" },
    { "value": "Europe/Berlin", "label": "Europe/Berlin (UTC+02:00)" },
    { "value": "Africa/Cairo", "label": "Africa/Cairo (UTC+02:00)" },
    { "value": "Europe/Moscow", "label": "Europe/Moscow (UTC+03:00)" },
    { "value": "Asia/Dubai", "label": "Asia/Dubai (UTC+04:00)" },
    { "value": "Asia/Karachi", "label": "Asia/Karachi (UTC+05:00)" },
    { "value": "Asia/Kolkata", "label": "Asia/Kolkata (UTC+05:30)" },
    { "value": "Asia/Dhaka", "label": "Asia/Dhaka (UTC+06:00)" },
    { "value": "Asia/Bangkok", "label": "Asia/Bangkok (UTC+07:00)" },
    { "value": "Asia/Singapore", "label": "Asia/Singapore (UTC+08:00)" },
    { "value": "Asia/Tokyo", "label": "Asia/Tokyo (UTC+09:00)" },
    { "value": "Australia/Sydney", "label": "Australia/Sydney (UTC+10:00)" },
    { "value": "Pacific/Auckland", "label": "Pacific/Auckland (UTC+12:00)" }
];
